auth:
  enablePostgresUser: true
  postgresPassword: "${postgres_password}"
  database: "${sonar_db_name}"
  username: "${sonar_db_username}"
  password: "${sonar_db_password}"
primary:
  persistence:
    enabled: true
metrics:
  enabled: true