
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# Scrape the Otel Collector's Prometheus exporter
scrape_configs:
  - job_name: otelcollector
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - otelcollector:8889