server:
  http_listen_port: 3200
  grpc_listen_port: 4319

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces