prometheusMonitoring:
  podMonitor:
    enabled: true
postgresql:
  enabled: false
  postgresqlServer: ${postgres_url}
  postgresqlDatabase: ${sonar_db_name}
  postgresqlUsername: ${sonar_db_username}
  postgresqlPassword: ${sonar_db_password}
persistence:
  enabled: true
ingress:
  enabled: true
  className: nginx
  hosts:
    - name: ${sonar_hostname}
      path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
sonarProperties:
  sonar.projectKey: "my-github-project"
  sonar.projectName: "My GitHub Project"
  sonar.projectDescription: "Automated scan of my GitHub repository"
  sonar.sources: "/backend,/frontend"
  sonar.java.binaries: "/backend/target"
  sonar.typescript.tsconfigPath: "/frontend/tsconfig.json"
  sonar.exclusions: "**/node_modules/**, **/dist/**"
  sonar.scm.provider: "git"
  sonar.scm.disabled: "false"
  sonar.qualitygate.wait: "true"
  sonar.qualitygate.timeout: "300"
  # GitHub Token Authentication (Stored securely in Kubernetes secrets)
  sonar.pullrequest.provider: "GitHub"
  sonar.pullrequest.github.endpoint: "https://github.com/andrislapins/vagrant-minikube-terraform-sonarqube.git"
  sonar.pullrequest.github.token.secured: "${GITHUB_TOKEN}"